### ISSUE TITLE
Next button is missing on 'More on REST APIs' topic

### ISSUE THREAD

**Issue by techwriter-pooja** [gautriv/apidocumentation#1]
Hi there!

I was going through your site, and I found the next button is missing on 'More on REST APIs' topic.

![image](https://github.com/gautriv/apidocumentation/assets/106590037/52a158d5-1b7b-4a30-8adf-204fa11f51a7)

**Comment by gautriv** [comment]
Thank you, Pooja.
Will add the **Next** button.

**Comment by gautriv** [comment]
Resolved!
